#! /bin/sh

# /etc/init.d/S19sda1
#
# mount ext3 partition on internal harddisk

cnt=20
dev=sda1
mountpoint=/tmp/usbmounts/$dev

# wait for devices to arrive
while [ "$cnt" -gt "0" ]
do
   let cnt=cnt-1
   if [ -e /dev/$dev ]
   then
      #mount device
      /bin/mkdir -p $mountpoint
      /bin/mount -t ext3 /dev/$dev $mountpoint
      #make device available in UI.
      #make disk show up on HDD section
      LIST="$(ls /tmp/usbmounts)";
      for i in $LIST
      do
        echo " /tmp/usbmounts/$i/label ";
        if [ -f /tmp/usbmounts/$i/label ]
        then
          ln -s /tmp/usbmounts/$i /tmp/ramfs/volumes/$i
          cp /tmp/usbmounts/$i/label /tmp/ramfs/labels/$i
        fi
      done
      break
   fi
   sleep 2
done

exit 0