#!/bin/sh

# *************
# Configuration
REMOTE="/opt/bin/transmission-remote"
USERNAME="admin"
PASSWORD="admin1234"
MAXDOWN="2"
MAXACTIVE="10"
CONFIG="/root/transmission/settings.json"

# *************
# Set-up variables
CMD="$REMOTE --auth $USERNAME:$PASSWORD"
LOGCMD="/usr/bin/logger -t transmission-queue "
MAXRATIO=$(cat $CONFIG | grep \"ratio-limit\":)
MAXRATIO=${MAXRATIO#*\"ratio-limit\": }
MAXRATIO=${MAXRATIO%*, }

RUNNING = "$(ps aux | grep transmission | wc -l)"
    
if [ RUNNING -gt 1 ]; then
   
   # *************
   # deal with downloads
   DOWNACTIVE="$($CMD -l | grep -v 100% | grep -v Sum | grep -v Stopped | grep -v "ID     Done" | wc -l)"
   if [ $MAXDOWN -lt $DOWNACTIVE ]; then
      DOWNTOSTOP="$($CMD -l  | grep -v 100% | grep -v Sum | grep -v Stopped | grep -v "ID     Done" | \
         tail -n $(expr $DOWNACTIVE - $MAXDOWN) | awk '{ print $1; }' | grep -v ID)"
      for ID in $DOWNTOSTOP; do
         NAME="$($CMD --torrent $ID --info | grep Name:)"
         $LOGCMD "<<< $ID: ${NAME#*Name: }"
         $CMD --torrent $ID --stop >> /dev/null 2>&1
      done
   else
      [ $(expr $MAXDOWN - $DOWNACTIVE) -gt 0 ] && (
      DOWNINACTIVE="$($CMD -l  | grep -v 100% | grep Stopped | grep -v "ID     Done" | wc -l)"
      [ $DOWNINACTIVE -gt 0 ] && (
         DOWNTOSTART="$($CMD -l  | grep -v 100% | grep Stopped | \
            head -n $(expr $MAXDOWN - $DOWNACTIVE) | awk '{ print $1; }' | grep -v ID)"
         for ID in $DOWNTOSTART; do
            NAME="$($CMD --torrent $ID --info | grep Name:)"
            $LOGCMD ">>> $ID: ${NAME#*Name: }"
            $CMD --torrent $ID --start >> /dev/null 2>&1
         done
         )
      )
   fi
   # Then deal with total active
   ACTIVE="$($CMD -l  | grep -v Sum | grep -v Stopped | grep -v "ID     Done" | wc -l)"
   if [ $MAXACTIVE -lt $ACTIVE ]; then
      TOSTOP="$($CMD -l  | grep 100% | grep -v Stopped | grep -v "ID     Done" | \
         tail -n $(expr $ACTIVE - $MAXACTIVE) | awk '{ print $1; }' | grep -v ID)"
      for ID in $TOSTOP; do
         NAME="$($CMD --torrent $ID --info | grep Name:)"
         $LOGCMD "<<< $ID: ${NAME#*Name: }"
         $CMD --torrent $ID --stop >> /dev/null 2>&1
      done
   else
      [ $(expr $MAXACTIVE - $ACTIVE) -gt 0 ] && (
      SEEDINACTIVE="$($CMD -l  | grep 100% | grep Stopped | grep -v "ID     Done" | \
         awk -v ratio=$MAXRATIO '{ if (strtonum(substr($0,52,4)) < ratio) print $0 ;}' | wc -l)"
      [ $SEEDINACTIVE -gt 0 ] && (
         TOSTART="$($CMD -l  | grep 100% | grep Stopped | \
            awk -v ratio=$MAXRATIO '{ if (strtonum(substr($0,52,4)) < ratio) print $0 ;}' | \
            head -n $(expr $MAXACTIVE - $ACTIVE) | awk '{ print $1; }' | grep -v ID)"
         for ID in $TOSTART; do
            NAME="$($CMD --torrent $ID --info | grep Name:)"
            $LOGCMD ">>> $ID: ${NAME#*Name: }"
            $CMD --torrent $ID --start >> /dev/null 2>&1
         done
         )
      )
   fi
fi